backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Dato", name: "date", widget: "datetime"}
      - {label: "Billede", name: "image", widget: "image", required: false}
      - {label: "Kort beskrivelse", name: "excerpt", widget: "text"}
      - {label: "Indhold", name: "body", widget: "markdown"}

  - name: "cases"
    label: "Cases"
    folder: "cases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Dato", name: "date", widget: "datetime"}
      - {label: "Opgave", name: "task", widget: "text"}
      - {label: "Resultat", name: "result", widget: "text"}
      - {label: "Detaljeret beskrivelse", name: "body", widget: "markdown"}
